# Site settings

title: 1D Rainbow Bondage Bear &amp; Sugar Bear
description: 1D Rainbow Bondage Bear &amp; Sugar Bear
baseurl: "/rbb/" # the subpath of your site, e.g. /blog/
url: "http://beccasafan.github.io" # the base hostname & protocol for your site
twitter_username: beccasafan
github_username:  beccasafan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
exclude: ["old"]

collections:
  props:
    output: true

sass:
  sass_dir: content/styles/
  style: compressed

host: 0.0.0.0

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "concert"
      permalink: "concerts/:year/:month/:title"
      twitterCard:
        cardType: summary_large_image
        excerpt: "{{ page.date | date: '%Y-%m-%d' }}{% if page.excerpt %} {{ page.excerpt }}{% endif %}"
  -
    scope:
      path: ""
      type: props
    values:
      permalink: "props/:path/"
      layout: prop
      twitterCard:
        cardType: summary_large_image
        excerpt: "Prop.{% if page.excerpt %} {{ page.excerpt }}{% endif %}"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"